apiVersion: eksctl.io/v1alpha4
kind: ClusterConfig

metadata:
  name: acme-cluster
  region: us-west-2

nodeGroups:
  - name: acme-node-1
    instanceType: m5.large
    desiredCapacity: 2
    privateNetworking: true