apiVersion: apps/v1
kind: Deployment
metadata:
  name: acme-ui
  labels:
    app: acme-ui
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: acme-ui
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: acme-ui
    spec:
      containers:
      - image: acme/ui
        imagePullPolicy: Always
        name: acme-ui
        ports:
        - containerPort: 3000
          protocol: TCP
