apiVersion: apps/v1
kind: Deployment
metadata:
  name: acme-api
  labels:
    app: acme-api
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: acme-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: acme-api
    spec:
      containers:
      - image: acme/api
        imagePullPolicy: Always
        name: acme-api
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
        - name: POSTGRES_URL
          value: "Postgresql DB URL"
        - name: METRICS_URL
          value: "Prometheus URL"
        args: ["$(POSTGRES_URL) $(METRICS_URL)"]